### PR TITLE
Add Dean Langsam

### PR DESCRIPTION
**Pull request by boedybios**
Add Dean Langsam - Regular Talk

### CODE REVIEW

**Comment by adifdwimaulana** [comment]
Please to save the speaker's image at themes/eventalk/static/img/speakers

**Review by adifdwimaulana — CHANGES_REQUESTED** [review]
Please to save the speaker's image at themes/eventalk/static/img/speakers

**Comment by boedybios** [comment]
> Please to save the speaker's image at themes/eventalk/static/img/speakers

done :)

**Comment by adifdwimaulana** [comment]
Thank you mas Budi :)

**Comment by adifdwimaulana** [comment]
Thank you mas Budi. Your PR has been merged :)

**Comment by boedybios** [comment]
> Thank you mas Budi. Your PR has been merged :)

Berarti  sudah oke ya.
Aku coba lanjut dech sekalian bantu2 :)

**Comment by adifdwimaulana** [comment]
siap terimakasih mas, untuk yang regular speaker di speakers.md urutan sosmednya linkedin, github, twitter ya mas
Jadi title, speaker name, speaker image, slug, linkedin, github, twitter. Barusan ada beberapa adjustment soalnya

**Pull request merged**
